Update VoxelShape Generators to Actual MojMaps and added Yarn.
JannisX11/blockbench-plugins pull request #473
Opened 2024-02-05 17:23 UTC by Nyfaria

It was still using MCP class names, Mojang Class names are now Available for use (have been for a while), so I updated it to use the Mojang Class names, and Added Yarn.

2024-02-05 17:38 UTC, Nyfaria commented
@Spectre0987 I made this PR and just want to let you know.

2024-05-08 20:42 UTC, JannisX11 requested changes

2024-05-08 20:42 UTC, JannisX11 commented on plugins/voxel_shape_generator.js
> +        version: '0.2.0',
Make sure to update the version number and general metadata in plugins.json as well.

2024-05-08 20:42 UTC, JannisX11 commented on plugins/voxel_shape_generator.js
> +                default: 'Mojang Mappings'
This should point to the key, not the value. So "momap". You can also omit it entirely, that way the first option will be the default.

2024-05-09 01:04 UTC, Nyfaria commented
I have made requested changes

2024-05-09 10:00 UTC, merged