Cosmic Reach Model Editor plugin
JannisX11/blockbench-plugins pull request #506
Opened 2024-04-10 18:25 UTC by zHoeshin

Add the Cosmic Reach Model Editor plugin to the list of Blockbench plugins

2024-04-11 03:53 UTC, Malik12tree requested changes

2024-04-11 03:53 UTC, Malik12tree commented on plugins.json
> +		"new_repository_format": true,
The plugin's meta data is mismatched with the meta data defined in the code. (mismatched `tags`, missing `min_version`, `variant`, `creation_date`, `new_repository_format`)
```js
    Plugin.register(id, {
      title: name,
      icon: "icon.png",
      author: "Z. Hoeshin",
      description: "Allows creating, editing, importing and exporting Cosmic Reach block models.",
      tags: [],
      version: "1.1.0",
      creation_date: "2024-03-09",
```

2024-04-11 03:53 UTC, Malik12tree commented on plugins/cosmic_reach_model_editor/cosmic_reach_model_editor.js
> +		}
You should not directly overwrite the condition for the load filter, as its internal condition is subject to change whether inside Blockbench or an another plugin. You should store the original condition and make use of it inside the overwritten condition.

Define a reference in the plugin's scope.
```js
let originalJavaBlockLoadFilter;
```
```suggestion
        originalJavaBlockLoadFilter = Codecs.java_block.load_filter.condition;
        Codecs.java_block.load_filter.condition = (model) => {
		return originalJavaBlockLoadFilter(model)  && (!model.cuboids);
	}
```
And do not forget onunload to reset the condition..
```js
Codecs.java_block.load_filter.condition = originalJavaBlockLoadFilter;
```

2024-04-11 03:53 UTC, Malik12tree commented on plugins/cosmic_reach_model_editor/cosmic_reach_model_editor.js
> +    let codec, format, export_action, import_action, dialog, properties
`sumArray` should be defined in the plugin's local scope and not exposed globally.
```suggestion
(() => {
    function sumArrays(a, b){
        s = []
        for(let i = 0; i < Math.min(a.length, b.length); i++){
            s.push(a[i] + b[i])
        }
        return s
    }
    let codec, format, export_action, import_action, dialog, properties
```

2024-04-11 05:18 UTC, Malik12tree commented
Please make use of `originalJavaBlockCond`, To clarify again, the original condition might be changed within Blockbench or by other plugins. Instead, use the saved condition within your new condition. This will protect your plugin from breaking Blockbench or other plugins in the future.

2024-04-11 12:19 UTC, Malik12tree commented
Yeah of course! But only to give your plugin more availability in case the original condition (`model.parent || model.elements || model.textures`) changes, instead of hard coding it in your code, just change it to call the original condition. It will behave exactly as it's behaving now, only less subject to break things in the future.

```js
(mode) => {
    return !mode.cuboids && originalJavaBlockCond(model);
}
```

2024-04-13 13:46 UTC, zHoeshin commented
@Malik12tree , the issue's long ago fixed

2024-04-13 13:53 UTC, Malik12tree commented
@zHoeshin Yeah totally aware. Jannis is the only person that can merge pull requests in this repo, sometimes pull requests may take long if he's busy

2024-04-19 20:17 UTC, JannisX11 commented
Thanks for your help @Malik12tree !

There are two breaking issure remaining:
* `Codec.java_block` does not exist. Use `Codecs.java_block` instead in the 2 places where it's misspelled
* plugins.json has a trailing comma, as you can seen from the automatic check above

I would also strongly recommend to add icons to your model format and your actions.
Once this is fixed, you may update the creation date field to the current date so it'll show up as new.

2024-04-25 13:10 UTC, JannisX11 commented
The new icons are not working correctly.
It's a good practice to always test all the changes that you make.
![image](https://github.com/JannisX11/blockbench-plugins/assets/29278436/aa0115a5-4f00-42e6-aae9-247a9b59d19d)

2024-04-30 17:05 UTC, merged